// <auto-generated />
using System;
using H3SamuraiProject.Repo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace H3SamuraiProject.Repo.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240819114441_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("H3SamuraiProject.Repo.Models.Battles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Battles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The ultimate showdown in 1600 where samurais settled who was the top dog of the era, and it wasn't just a clash of swords—it was the medieval version of a big, dramatic TV finale.",
                            Name = "Battle of Sekigahara"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The 1575 face-off where gunpowder made its grand entrance, and Takeda’s cavalry learned the hard way that 'what goes around comes around'—usually in the form of bullets.",
                            Name = "Battle of Nagashino"
                        });
                });

            modelBuilder.Entity("H3SamuraiProject.Repo.Models.Clan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClanName = "Future Warriors",
                            Description = "A clan of elite samurais sent from the past to protect the future, renowned for their honor and combat skills."
                        },
                        new
                        {
                            Id = 2,
                            ClanName = "Shadow Blades",
                            Description = "A mysterious clan shrouded in secrecy, known for their stealth and formidable swordsmanship."
                        });
                });

            modelBuilder.Entity("H3SamuraiProject.Repo.Models.Horse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Horses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A blazing-fast horse with a mane as fiery as his name.",
                            Name = "Red Hare"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A majestic and mysterious steed with an air of elegance.",
                            Name = "ShadowFax"
                        });
                });

            modelBuilder.Entity("H3SamuraiProject.Repo.Models.Samurai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("ClanId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HorseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.HasIndex("HorseId");

                    b.ToTable("Samurais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 25,
                            ClanId = 1,
                            Description = "A samurai warrior who has been sent to the future by an evil demon named Aku.",
                            HorseId = 1,
                            Name = "Samurai Jack"
                        },
                        new
                        {
                            Id = 2,
                            Age = 15,
                            ClanId = 2,
                            Description = "Just another guy with sword.",
                            HorseId = 2,
                            Name = "DarkOne"
                        });
                });

            modelBuilder.Entity("H3SamuraiProject.Repo.Models.SamuraiBattles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BattleId")
                        .HasColumnType("int");

                    b.Property<int>("SamuraiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BattleId");

                    b.HasIndex("SamuraiId");

                    b.ToTable("SamuraiBattles");
                });

            modelBuilder.Entity("H3SamuraiProject.Repo.Models.Samurai", b =>
                {
                    b.HasOne("H3SamuraiProject.Repo.Models.Clan", "Clan")
                        .WithMany("Samurais")
                        .HasForeignKey("ClanId");

                    b.HasOne("H3SamuraiProject.Repo.Models.Horse", "Horse")
                        .WithMany()
                        .HasForeignKey("HorseId");

                    b.Navigation("Clan");

                    b.Navigation("Horse");
                });

            modelBuilder.Entity("H3SamuraiProject.Repo.Models.SamuraiBattles", b =>
                {
                    b.HasOne("H3SamuraiProject.Repo.Models.Battles", "Battle")
                        .WithMany("SamuraiBattles")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("H3SamuraiProject.Repo.Models.Samurai", "Samurai")
                        .WithMany("SamuraiBattles")
                        .HasForeignKey("SamuraiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Battle");

                    b.Navigation("Samurai");
                });

            modelBuilder.Entity("H3SamuraiProject.Repo.Models.Battles", b =>
                {
                    b.Navigation("SamuraiBattles");
                });

            modelBuilder.Entity("H3SamuraiProject.Repo.Models.Clan", b =>
                {
                    b.Navigation("Samurais");
                });

            modelBuilder.Entity("H3SamuraiProject.Repo.Models.Samurai", b =>
                {
                    b.Navigation("SamuraiBattles");
                });
#pragma warning restore 612, 618
        }
    }
}
