// <auto-generated />
using System;
using H3SamuraiProject.Repo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace H3SamuraiProject.Repo.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240523171509_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("H3SamuraiProject.Repo.Models.Horse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Horses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Red Hare"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ShadowFax"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Black Beauty"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Silver"
                        });
                });

            modelBuilder.Entity("H3SamuraiProject.Repo.Models.Samurai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HorseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HorseId");

                    b.ToTable("Samurais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A samurai warrior who has been sent to the future by the evil demon Aku",
                            HorseId = 1,
                            Name = "Samurai Jack"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Just another guy with sword.",
                            HorseId = 2,
                            Name = "DarkOne"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A wandering samurai with a heart of gold and a knack for getting into trouble",
                            HorseId = 3,
                            Name = "Ronin Ron"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A samurai who prefers lounging around to sword fighting, but still manages to get the job done",
                            HorseId = 4,
                            Name = "Lazy Blade Larry"
                        });
                });

            modelBuilder.Entity("H3SamuraiProject.Repo.Models.Samurai", b =>
                {
                    b.HasOne("H3SamuraiProject.Repo.Models.Horse", "Horse")
                        .WithMany()
                        .HasForeignKey("HorseId");

                    b.Navigation("Horse");
                });
#pragma warning restore 612, 618
        }
    }
}
